# _config.yml
# Site settings

domain: dbhart.github.io
url: https://dbhart.github.io
title: dbhart.github.io
email: dbhart@noreply.users.github.com
github_username:  dbhart
theme: null

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true