name: Test output creation

on:
  push:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:

    - name: Output to github output
      id: geturl
      run: |
        echo "ourl=https://sandialabs.github.io/sansmic/" >> "$GITHUB_OUTPUT"
        echo "URL=https://sandialabs.github.io/sansmic/" >> "$GITHUB_ENV"

    - name: Output to job summary
      run: |
        echo "### Summary Time!" >> $GITHUB_STEP_SUMMARY
        echo "The url I got was $URL" >> $GITHUB_STEP_SUMMARY
        echo 'The url output was" "${{ steps.geturl.outputs.ourl }}" >> $GITHUB_STEP_SUMMARY
