name: Test output creation

on:
  push:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      url: ${{ steps.get-url.outputs.url }}

    steps:

    - name: Output to github output
      id: get-url
      run: |
        echo "url=https://sandialabs.github.io/sansmic/" >> "$GITHUB_OUTPUT"

    - name: Output to job summary
      run: |
        echo "### Summary Time!" >> $GITHUB_STEP_SUMMARY
        echo "The url I got was $url" >> $GITHUB_STEP_SUMMARY
